//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/BoundingControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BoundingControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BoundingControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BoundingControls"",
    ""maps"": [
        {
            ""name"": ""Bounding"",
            ""id"": ""a996b9ee-f26a-4044-82c1-1122a75d0871"",
            ""actions"": [
                {
                    ""name"": ""Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""99f4ff68-74b2-447f-bf26-3e4aabf601c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3dca3528-ef03-4e27-8eec-a3f4f0be4ca4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Bounding
        m_Bounding = asset.FindActionMap("Bounding", throwIfNotFound: true);
        m_Bounding_Toggle = m_Bounding.FindAction("Toggle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bounding
    private readonly InputActionMap m_Bounding;
    private IBoundingActions m_BoundingActionsCallbackInterface;
    private readonly InputAction m_Bounding_Toggle;
    public struct BoundingActions
    {
        private @BoundingControls m_Wrapper;
        public BoundingActions(@BoundingControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Toggle => m_Wrapper.m_Bounding_Toggle;
        public InputActionMap Get() { return m_Wrapper.m_Bounding; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BoundingActions set) { return set.Get(); }
        public void SetCallbacks(IBoundingActions instance)
        {
            if (m_Wrapper.m_BoundingActionsCallbackInterface != null)
            {
                @Toggle.started -= m_Wrapper.m_BoundingActionsCallbackInterface.OnToggle;
                @Toggle.performed -= m_Wrapper.m_BoundingActionsCallbackInterface.OnToggle;
                @Toggle.canceled -= m_Wrapper.m_BoundingActionsCallbackInterface.OnToggle;
            }
            m_Wrapper.m_BoundingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Toggle.started += instance.OnToggle;
                @Toggle.performed += instance.OnToggle;
                @Toggle.canceled += instance.OnToggle;
            }
        }
    }
    public BoundingActions @Bounding => new BoundingActions(this);
    public interface IBoundingActions
    {
        void OnToggle(InputAction.CallbackContext context);
    }
}
